<!DOCTYPE html>
<html>
<head>
    <title>Products Report - {{ now()->format('Y-m-d') }}</title>
    <style>
        body { font-family: Arial, sans-serif; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .low-stock { background-color: #ffdddd; }
        .header { text-align: center; margin-bottom: 20px; }
        .badge {
            padding: 3px 6px;
            border-radius: 3px;
            font-size: 11px;
            font-weight: bold;
        }
        .badge-danger { background-color: #dc3545; color: white; }
        .badge-warning { background-color: #ffc107; color: #212529; }
    </style>
</head>
<body>
    <div class="header">
        <h1>EDUC Pharmacy - Products Report</h1>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Brand</th>
                <th>Category</th>
                <th>Qty</th>
                <th>Alert Qty</th>
                <th>Status</th>
                <th>Order Price</th>
                <th>Selling Price</th>
                <th>Expiry Date</th>
                <th>Seller</th>
                <th>Purchases</th>
                <th>Last Restock</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
            @php
                $isLowStock = $product->quantity <= $product->alert_quantity;
                $expiryStatus = null;
                if ($product->expiry_date) {
                    $expiryDays = now()->diffInDays(Carbon\Carbon::parse($product->expiry_date), false);
                    if ($expiryDays < 0) {
                        $expiryStatus = 'Expired';
                    } elseif ($expiryDays <= 30) {
                        $expiryStatus = 'Soon';
                    }
                }
            @endphp
            <tr class="{{ $isLowStock ? 'low-stock' : '' }}">
                <td>{{ $product->name }}</td>
                <td>{{ $product->brand ?? '-' }}</td>
                <td>{{ $product->category ?? '-' }}</td>
                <td>{{ $product->quantity }}</td>
                <td>{{ $product->alert_quantity }}</td>
                <td>
                    @if($isLowStock)
                        <span class="badge badge-danger">LOW STOCK</span>
                    @else
                        <span>In Stock</span>
                    @endif
                </td>
                <td>{{ number_format($product->order_price, 2) }}</td>
                <td>{{ number_format($product->selling_price, 2) }}</td>
                <td>
                    @if($product->expiry_date)
                        {{ Carbon\Carbon::parse($product->expiry_date)->format('Y-m-d') }}
                        @if($expiryStatus)
                            <span class="badge badge-{{ $expiryStatus == 'Expired' ? 'danger' : 'warning' }}">
                                {{ $expiryStatus }}
                            </span>
                        @endif
                    @else
                        -
                    @endif
                </td>
                <td>{{ $product->seller ?? '-' }}</td>
                <td>{{ $product->purchase_frequency }}</td>
                <td>{{ $product->last_restock_date ? $product->last_restock_date->format('Y-m-d') : 'Never' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 30px; font-size: 11px; text-align: right;">
        <p>Generated by EDUC Pharmacy Management System</p>
    </div>
</body>
</html>